language: ruby

rvm:
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - ruby-head

gemfile:
  - activerecord_3_0.gemfile
  - activerecord_3_1.gemfile
  - activerecord_3_2.gemfile
  - activerecord_4_1.gemfile

matrix:
  allow_failures:
    - rvm: ruby-head
